Hotfix/generator manager
Parabeac/parabeac_core pull request #3
Opened 2020-08-21 22:43 UTC by SushiRoll53

Generator was not generating variables, constructor nor dependencies.
First cause was the fact that generator had multiple managers, so whenever a variable, constructor or dependency were added to the manager, was getting lost. In other words, the manager helping writing the files was not the same manager receiving the fields.
This PR removed the unnecessary managers, helped plugins to be more easy to understand, & cleaned the code a bit.

2020-08-23 00:40 UTC, Ihuds577 commented on lib/controllers/interpret.dart
> +    // _interpret._generationManager = PBFlutterGenerator(PBFlutterWriter());
Don't leave in commented code, if possible

2020-08-23 00:40 UTC, Ihuds577 commented on lib/controllers/interpret.dart
> +    // currentContext.generationManager = _generationManager;
Don't leave in commented code, if possible

2020-08-23 00:40 UTC, Ihuds577 commented on lib/controllers/interpret.dart
> +    // currentContext.generationManager = _generationManager;
Don't leave in commented code, if possible

2020-08-23 00:40 UTC, Ihuds577 commented on lib/generation/flutter_project_builder/flutter_project_builder.dart
> +          // intermediateItem.node.generator.manager = flutterGenerator;
Same as above.

2020-08-23 00:41 UTC, Ihuds577 commented on lib/generation/generators/layouts/pb_scaffold_gen.dart
> +  // final PBGenerationManager manager;
Also same as above.

2020-08-23 00:42 UTC, Ihuds577 commented on lib/interpret_and_optimize/entities/inherited_scaffold.dart
> -  // PBNakedPluginNode generatePluginNode(
Why is this entire block commented out?

2020-08-23 00:43 UTC, Ihuds577 requested changes
See comments in code.

2020-08-23 21:09 UTC, SushiRoll53 commented on lib/interpret_and_optimize/entities/inherited_scaffold.dart
> -  // PBNakedPluginNode generatePluginNode(
Nothing was using it, so I remove it. 
PD: I am also cleaning the other comments

2020-08-23 21:57 UTC, Ihuds577 approved these changes
Looks good to me!

2020-08-24 06:45 UTC, x64Eddie approved these changes

2020-08-24 06:47 UTC, merged